Vagrant.configure("2") do |config|
  config.vm.define "centos1" do |centos1|
    centos1.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable:true
    centos1.vm.hostname = "centos-machine1"
    centos1.vm.network "private_network", ip: "192.168.60.97"
    centos1.vm.provider "virtualbox" do |vb|
      vb.memory = 3000
      vb.linked_clone = true
      vb.name = "centos1"
    end
  end

  config.vm.define "centos2" do |centos2|
    centos2.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable:true
    centos2.vm.hostname = "centos-machine2"
    centos2.vm.network "private_network", ip: "192.168.60.98"
    centos2.vm.provider "virtualbox" do |vb|
      vb.memory = 3000
      vb.linked_clone = true
      vb.name = "centos2"
    end
  end

  config.vm.define "grafana" do |grafana|
    grafana.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable:true
    grafana.vm.hostname = "grafana-machine"
    grafana.vm.network "private_network", ip: "192.168.60.100"
    grafana.vm.provider "virtualbox" do |vb|
      vb.memory = 3000
      vb.linked_clone = true
      vb.name = "grafana"
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable:true
    ubuntu.vm.hostname = "ubuntu-machine"
    ubuntu.vm.network "private_network", ip: "192.168.60.99"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = 1000
      vb.linked_clone = true
      vb.name = "ubuntu"
    end
  end
end
